### YamlMime:Lifecycle
metadata:
  title: 'Windows डेस्कटॉप के लिए Microsoft Application Virtualization Hosting 5.1 '
  description: Windows डेस्कटॉप के लिए Microsoft Application Virtualization Hosting 5.1 निश्चित जीवनचक्र नीति का अनुसरण करता है.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: 'Windows डेस्कटॉप के लिए Microsoft Application Virtualization Hosting 5.1 '
summary: |+
  Windows डेस्कटॉप के लिए Microsoft Application Virtualization Hosting 5.1 [निश्चित](/lifecycle/policies/fixed) जीवनचक्र नीति का अनुसरण करता है.

  यह निम्नलिखित संस्करणों पर लागू होता है: Windows डेस्कटॉप के लिए

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>लिंक 
  * [उत्पाद की जानकारी](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>संस्करण 
  * Windows डेस्कटॉप के लिए