### YamlMime:Lifecycle
metadata:
  title: Windows डेस्कटॉप के लिए Microsoft एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6
  description: Windows डेस्कटॉप के लिए Microsoft एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6 फिक्स्ड लाइफसाइकल नीति का पालन करता है.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 3d5789104bc3b52d4ccfb836df52ddd2ab576d4e
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hi-IN
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4153925"
name: Windows डेस्कटॉप के लिए Microsoft एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6
summary: >+
  Windows डेस्कटॉप के लिए Microsoft एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6 [फिक्स्ड](/lifecycle/policies/fixed) लाइफसाइकल का पालन करता है.


  यह निम्नलिखित संस्करणों पर लागू होता है: Windows डेस्कटॉप के लिए

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>लिंक \n* [उत्पाद और माइग्रेशन की जानकारी](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [सर्विस पैक पॉलिसी](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> चूंकि App-V 4.6 क्लाइंट App-V 4.5 सर्वर उपयोग करता है, तो समर्थित App-V 4.6 क्लाइंट के साथ उपयोग में होने पर App-V 4.5 सर्वर का समर्थन करना App-V 4.6 के लाइफसाइकल दिनांक तक जारी रहेगा.\n\n## <a name=\"editions\"></a>संस्करण \n* Windows डेस्कटॉप के लिए"
