### YamlMime:Lifecycle
metadata:
  title: Windows डेस्कटॉप के लिए Microsoft एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6
  description: Windows डेस्कटॉप के लिए Microsoft एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6 फिक्स्ड लाइफसाइकल नीति का पालन करता है.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: hi-IN
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "821112"
name: Windows डेस्कटॉप के लिए Microsoft एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6
summary: >+
  Windows डेस्कटॉप के लिए Microsoft एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6 [फिक्स्ड](/lifecycle/policies/fixed) लाइफसाइकल का पालन करता है.


  यह निम्नलिखित संस्करणों पर लागू होता है: Windows डेस्कटॉप के लिए

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>लिंक \n* [उत्पाद और माइग्रेशन की जानकारी](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [सर्विस पैक पॉलिसी](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> चूंकि App-V 4.6 क्लाइंट App-V 4.5 सर्वर उपयोग करता है, तो समर्थित App-V 4.6 क्लाइंट के साथ उपयोग में होने पर App-V 4.5 सर्वर का समर्थन करना App-V 4.6 के लाइफसाइकल दिनांक तक जारी रहेगा.\n\n## <a name=\"editions\"></a>संस्करण \n* Windows डेस्कटॉप के लिए"
