### YamlMime:Lifecycle
metadata:
  title: विंडोज डेस्कटॉप के लिए माइक्रोसॉफ्ट एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6
  description: विंडोज डेस्कटॉप के लिए माइक्रोसॉफ्ट एप्लीकेशन वर्चुअलाइजेशन होस्टिंग होस्टिंग 4.6 फिक्स्ड लाइफसाइकिल पॉलिसी का पालन करती है।
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: hi-IN
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "821112"
name: विंडोज डेस्कटॉप के लिए माइक्रोसॉफ्ट एप्लीकेशन वर्चुअलाइजेशन होस्टिंग 4.6
summary: >+
  विंडोज डेस्कटॉप के लिए माइक्रोसॉफ्ट एप्लीकेशन वर्चुअलाइजेशन होस्टिंग होस्टिंग 4.6 [फिक्स्ड](/lifecycle/policies/fixed) लाइफसाइकिल पॉलिसी का पालन करती है।


  यह निम्नलिखित संस्करणों पर लागू होता है: विंडोज डेस्कटॉप के लिए

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>लिंक \n* [उत्पाद और माइग्रेशन की जानकारी](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [सर्विस पैक पॉलिसी](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> चूंकि ऐप-वी 4.6 क्लाइंट ऐप-वी 4.5 सर्वर का उपयोग करता है, इसलिए ऐप-वी 4.5 सर्वर को समर्थित ऐप-वी 4.6 क्लाइंट के साथ उपयोग करने पर ऐप-वी 4.6 की जीवनचक्र तिथियों के अनुसार समर्थित किया जाना जारी रहेगा।\n\n## <a name=\"editions\"></a>संस्करण \n* विंडोज डेस्कटॉप के लिए"
