### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 R2 Configuration Manager
  description: 'Microsoft System Center 2012 R2 Configuration Manager निश्चित जीवनचक्र नीति का अनुसरण करता है। '
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: 9e7bbf1db9f64b796da4e0c31bf66ce1b7dea0367121fbaeb1f2f41e60a20772
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: hi-IN
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2523674"
name: Microsoft System Center 2012 R2 Configuration Manager
summary: "Microsoft System Center 2012 R2 Configuration Manager [निश्चित](/lifecycle/policies/fixed) जीवनचक्र नीति का अनुसरण करता है। \n\n\n"
products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>लिंक \n* [सर्विस पैक पॉलिसी](/lifecycle/policies/fixed#service-packs)\n* [Configuration Manager के लिए दस्तावेजीकरण ](/mem/configmgr/core/misc/online-documentation)\n* [माइग्रेशन मार्गदर्शन](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
