### YamlMime:Lifecycle
metadata:
  title: पिक्सलसेंस एप्लीकेशन सूट 1.0
  description: पिक्सलसेंस एप्लीकेशन सूट 1.0 निश्चित जीवनचक्र नीति का अनुसरण करता है.
  ms.date: 08/12/2020
  ms.openlocfilehash: 3f929410194b40d875c8bb3618144739536874e1
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hi-IN
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4143639"
name: पिक्सलसेंस एप्लीकेशन सूट 1.0
summary: >+
  पिक्सलसेंस एप्लीकेशन सूट 1.0 [निश्चित](/lifecycle/policies/fixed) जीवनचक्र नीति का अनुसरण करता है.


products:
- windows
policyType: fixed
supportDates:
  start: 2009-01-01T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 1
  startDate: 2009-08-09T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2009-01-01T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
content: ''
