### YamlMime:Lifecycle
metadata:
  title: व्हेल कम्युनिकेशन इंटेलीजेंट एप्लीकेशन गेटवे
  description: व्हेल कम्युनिकेशन इंटेलीजेंट एप्लीकेशन गेटवे निश्चित जीवनचक्र नीति का पालन करता है|
  ms.date: 08/21/2020
  ms.openlocfilehash: 24af584653eafe614a9dd064d02e63f59ef5665a
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hi-IN
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4105270"
name: व्हेल कम्युनिकेशन इंटेलीजेंट एप्लीकेशन गेटवे
summary: >+
  व्हेल कम्युनिकेशन इंटेलीजेंट एप्लीकेशन गेटवे [निश्चित](/lifecycle/policies/fixed) जीवनचक्र नीति का पालन करता है.


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 2007-10-10T00:00:00.000-08:00
  end: 2010-07-13T22:59:59.999-08:00
releases:
- version: "3.1"
  startDate: 2007-10-10T00:00:00.000-08:00
  endDate: 2008-07-08T22:59:59.999-08:00
- version: "3.6"
  startDate: 2007-10-10T00:00:00.000-08:00
  endDate: 2010-07-13T22:59:59.999-08:00
content: "\n\n> [!NOTE]\n> इस उत्पाद के लिए समर्थन इसके अधिग्रहण की शर्तों के अधीन है।"
